services:
  mydramalist-bot:
    build: .
    container_name: mydramalist-bot
    restart: unless-stopped
    environment:
      - PYTHONPATH=/usr/src/app
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: mydramalist-redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

volumes:
  redis-data:

networks:
  bot-network:
    driver: bridge
