services:
  mydramalist-bot:
    build: .
    container_name: mydramalist-bot
    restart: unless-stopped
    environment:
      - PYTHONPATH=/usr/src/app
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: mydramalist-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - bot-network

volumes:
  redis-data:

networks:
  bot-network:
    driver: bridge
